### ISSUE TITLE
panic if searching in non-existing files

### ISSUE THREAD

**Issue by lasseoe** [jwtly10/varip#1]
There's no file called "/home/lasseoe/allowPrivilegeEscalation", it shouldn't panic but fail nicely and/or continue to the next file.

$ ./varip-linux-amd64 allowPrivilegeEscalation contour-values.yaml
Searching for pattern 'contour-values.yaml' in /home/lasseoe/allowPrivilegeEscalation

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x5b371f]

goroutine 1 [running]:
main.search.func1({0xc0001b8000, 0x26}, {0x0, 0x0}, {0x657c18?, 0xc00010e9f0?})
	/home/runner/work/varip/varip/main.go:98 +0x11f
path/filepath.WalkDir({0xc0001b8000, 0x26}, 0xc000171ac8)
	/opt/hostedtoolcache/go/1.22.1/x64/src/path/filepath/path.go:531 +0x9c
main.search({0xc0001b8000, 0x26}, 0x8?, 0xa8?)
	/home/runner/work/varip/varip/main.go:91 +0x65
main.main.func1(0xc00011a480)
	/home/runner/work/varip/varip/main.go:78 +0x2f0
github.com/urfave/cli/v2.(*Command).Run(0xc0001ac160, 0xc00011a480, {0xc00010e060, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x97d
github.com/urfave/cli/v2.(*App).RunContext(0xc0001a2200, {0x658710, 0x814e80}, {0xc00010e060, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/home/runner/work/varip/varip/main.go:82 +0x22c

**Comment by jwtly10** [comment]
Thanks for the issue @lasseoe 

I overlooked a few things due to the very bespoke use case I was using it for.... 

Theres a few edge cases that require quick fixes.

Thanks for highlighting this
